# Theme based on https://github.com/pages-themes/hacker

title: MAUPIN.TEL
email: research@maupin.tel
description: rainbows and flying objects # >- this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed
markdown: kramdown
exclude:
  - hacker/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
